bug fixes
The input path is multiple.
The following is the output:
putting data onto: cuda:0
using fine_tune model: /root/.romp/TRACE_models/trace_image_backbone.pkl
missing parameters of layers:[]
self.conf_thresh 0.05
using fine_tune model: /root/.romp/TRACE_models/trace_head.pkl
copy param _result_parser.params_map_parser.smpl_model.vertex_joint_selector.extra_joints_idxs failed, mismatched
missing parameters of layers:[]
Loading 11 image sequences to process
<trace2.utils.load_data.InternetVideo object at 0x7fd11ef01130>
Processing ['./demo/trace_demo/']
[ WARN:0@5.612] global loadsave.cpp:248 findDecoder imread_('./demo/trace_demo/./demo/trace_demo/00000.jpg'): can't open/read file: check file path/integrity
image load None ./demo/trace_demo/./demo/trace_demo/00000.jpg
Traceback (most recent call last):
  File "/root/miniconda3/envs/ngp/bin/trace2", line 33, in <module>
    sys.exit(load_entry_point('simple-romp==2.0.2', 'console_scripts', 'trace2')())
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/main.py", line 145, in main
    outputs, tracking_results, kp3d_results, imgpaths = trace(sequence_dict)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/main.py", line 103, in forward
    for meta_data in data_loader:
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/utils/load_data.py", line 130, in __getitem__
    return self.collect_entire_sequence_inputs(index)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/utils/load_data.py", line 110, in collect_entire_sequence_inputs
    frame_data[cid] = self.get_item_single_frame(fid, augment_cfgs=augment_cfgs)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/utils/load_data.py", line 88, in get_item_single_frame
    input_data = img_preprocess(image, imgpath, input_size=512)
  File "/root/miniconda3/envs/ngp/lib/python3.8/site-packages/trace2/utils/load_data.py", line 142, in img_preprocess
    image = image[:,:,::-1]
TypeError: 'NoneType' object is not subscriptable